services:
  db:
    hostname: test-scalable-path-db
    image: postgres:13.7-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root_pw
      - POSTGRES_DB=scalable_path
    ports:
      - 5432:5432
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5